bin: loacte emacs before run
Signed-off-by: Shachar Sharon <synarete@xxxxxxxx>

diff --git a/bin/em b/bin/em
--- a/bin/em
+++ b/bin/em
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
 set -e
 export GTK_THEME=Adwaita:dark
+command -v emacs || (echo "emacs is missing" && exit 1)
 exec emacs --no-splash "$@" > /dev/null 2>&1 &
diff --git a/bin/tem b/bin/tem
--- a/bin/tem
+++ b/bin/tem
@@ -5,4 +5,5 @@ export LANGUAGE=en_US.UTF-8
 export COLORTERM=truecolor
 export TERM=xterm-256color
 export ESHELL="/bin/bash"
-emacs --no-window-system --no-splash "$@"
+command -v emacs-nw || (echo "emacs-nw is missing" && exit 1)
+emacs-nw "$@"
