bash: Defined rfindc as function

diff --git a/bash/bash_functions b/bash/bash_functions
--- a/bash/bash_functions
+++ b/bash/bash_functions
@@ -1,65 +1,69 @@
 # Common helpers
 yell() {
-	echo "$0: $*" >&2;
+  echo "$0: $*" >&2;
 }
 die() {
-	yell "$*"; exit 1;
+  yell "$*"; exit 1;
 }
 try() {
-	"$@" || die "Failed to execute: $*";
+  "$@" || die "Failed to execute: $*";
 }
 
 # Emacs helpers
 emacsclnt() {
-	emacsclient -t -a "" $@
+  emacsclient -t -a "" $@
 }
 
 emacsd_start() {
-	emacs --daemon
+  emacs --daemon
 }
 
 emacsd_stop() {
-	emacsclient --eval '(kill-emacs)'
+  emacsclient --eval '(kill-emacs)'
 }
 
 # Use 'most' pager for man
-man() {
-	env MANPAGER="most -s" man "$@"
+mman() {
+  env MANPAGER="most -s" man "$@"
 }
 
 # Run Vim with less.vim. Read stdin if no arguments were given.
 vmore() {
-	if test $# = 0; then
-		vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' -
-	else
-		vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' "$@"
-	fi
+  if test $# = 0; then
+    vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' -
+  else
+    vim --cmd 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' "$@"
+  fi
 }
 
 # Top by process-name
 ptop() {
-	name="$1"
-	if [ -z "${name}" ]; then
-    		return
-	fi
-	pids=$(pgrep -d',' -x ${name})
-	if [ -z "${pids}" ]; then
-		return
-	fi
-	top -p ${pids}
+  name="$1"
+  if [ -z "${name}" ]; then
+    return
+  fi
+  pids=$(pgrep -d',' -x ${name})
+  if [ -z "${pids}" ]; then
+    return
+  fi
+  top -p ${pids}
 }
 
 # Show installed packages using white-seperator delimiter
 rpmqaf() {
-	rpm -qa --qf "%{NAME} %{VERSION} %{RELEASE} %{VENDOR}\n"
+  rpm -qa --qf "%{NAME} %{VERSION} %{RELEASE} %{VENDOR}\n"
 }
 
 # Show content of rpm file
 rpmdump() {
-	for f in "$@"; do
-		try rpm2cpio "${f}" | cpio -tv
-	done
+  for f in "$@"; do
+    try rpm2cpio "${f}" | cpio -tv
+  done
 }
 
-
-
+# Find C files at
+rfindc() {
+  for d in "$@"; do
+    find ${d} -type f -name "*.[ch]"
+  done
+}
